name: Process PlantUML

on: [push, pull_request]

jobs:
  plantuml:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: compile markdown source
        uses: kfiry77/mdcompile@latest
        with:
          output_dir: "doc"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "compile markdown source"
